.TH COMMAND-NOT-FOUND "8" "November 2010" "command-not-found 0.2.38"
.SH NAME
command\-not\-found \- suggest installation of packages in interactive bash sessions.
.SH SYNOPSIS
.B command\-not\-found
[\fB\-\-help\fR]
[\fB\-\-ignore\-installed\fR]
.SH DESCRIPTION
.B command\-not\-found
will install handler for command_not_found that looks up programs not currently installed but available from the repositories.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help\fR
Shows help options.
.TP
.BR \-\-ignore\-installed\fR
ignore local binaries and display the available packages.
.SH AUTHOR
.PP
This manual page was written by Vincent Cheng <Vincentc1208@gmail.com>, for the Debian project (and may be used by others).
