.TH update-command-not-found 8 "2017-11-13" "0-1" "Command not found helper"

.SH NAME
update-command-not-found \- update the command-not-found cache

.SH SYNOPSIS
.B update-command-not-found

.SH DESCRIPTION
.B update-command-not-found
updates the cache (database) for command-not-found using the Contents
files in /var/lib/apt/lists/, which are fetched by apt when apt-file is
installed.

.SH AUTHOR
command-not-found and update-command-not-found was written
by Shawn Landden <shawn@git.icu>, as a reimplementation of
command-not-found by Zygmunt Krynicki, and update-command-not-found
by Julian Andres Klode <jak@debian.org>
