#!/usr/bin/ruby
# (C) 2017 Shawn Landden, GPL-2+
#Create the databases (or cache) for command-not-found
#
#This program creates the database in /var/cache/command-not-found/dn. It may
#take some time, because the files it reads are big.
#
#Patches are accepted, as well as rewrites.
#
#RE2 makes this twice as fast
require 're2'
paths = RE2::Regexp.new('^(?:(?:bin\/)|(?:sbin\/)|(?:usr\/bin\/)|(?:usr\/sbin\/)|(?:usr\/games\/))')
parse = RE2::Regexp.new('^[^ \t]*\/([^ \t]*)[ \t]*[^ \t]*\/([^ \t]*)$')
db = []
Dir::entries("/var/lib/apt/lists").
	grep_v(/diff_Index$/).
	grep(RE2::Regexp.new("Contents-#{`dpkg --print-architecture`.chomp}")).each { |repo|

	component = repo.split('_')[-2]
	io = IO.popen(["/usr/lib/apt/apt-helper", "cat-file", "/var/lib/apt/lists/#{repo}"])
	io.grep(paths) { |line|
		match = parse.match(line)
		db << "#{match[1]}\xff#{match[2].chomp}/#{component.byteslice(0,2)}"
	}
}
db.sort!
out = open("/var/cache/command-not-found/db", "w+")
db.each { |i|
	out.write(i)
	out.putc("\n")
}
