#!/bin/sh
cd .. | exit
for dir in po/*.po
do
	dir=${dir%*/}
	[ -e "$dir" ] || continue
        LANGUAGE=`echo ${dir##*/} | sed 's/^command-not-found-\([^\.]*\).po$/\1/'`
#	echo $LANGUAGE
	mkdir -p "debian/command-not-found/usr/share/locale/$LANGUAGE/LC_MESSAGES"
	msgfmt po/${dir##*/} -o "debian/command-not-found/usr/share/locale/$LANGUAGE/LC_MESSAGES/command-not-found.mo"
#	echo $dir
done

#!/usr/bin/ruby
#Dir.entries("po").grep(/.po$/).each{ |i|
#       p i
#       language = /^command-not-found-([^.]*).po$/.match(i)[1]
#       `mkdir -p debian/command-not-found/usr/share/locale/#{language}/LC_MESSAGES`
#       `msgfmt po/#{i} -o debian/command-not-found/usr/share/locale/#{language}/LC_MESSAGES/command-not-found.mo`
#}

